name: Tests

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "tests/**"
      - "benches/**"
      - "examples/**"
      - "build.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/test.yml"
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "tests/**"
      - "benches/**"
      - "examples/**"
      - "build.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".github/workflows/test.yml"

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --locked
